#!/usr/bin/env python3
"""Generate music_clip.h: an original, license-free synthesised music loop for
NBFM TX loop tests. ~30 s, 8000 Hz, int8 PCM, 150–3400 Hz band-limited,
loop points on zero crossings. No samples, no third-party audio: everything is
synthesised here, so the output is CC0 / public domain.

Usage:  python3 gen_music_clip.py [--seconds 30] [--out ../music_clip.h] [--wav preview.wav]

Only for dummy-load / cable tests. Broadcasting music on the air is not
permitted under amateur radio regulations.
"""
import argparse, math
import numpy as np
from scipy import signal

FS = 8000

def note(n):            # MIDI note -> Hz
    return 440.0 * 2 ** ((n - 69) / 12)

def env(n, a, d, s, r, total):
    """ADSR envelope, times in samples."""
    e = np.zeros(total)
    a = max(1, a); d = max(1, d); r = max(1, r)
    e[:a] = np.linspace(0, 1, a)
    e[a:a+d] = np.linspace(1, s, d)
    e[a+d:total-r] = s
    e[total-r:] = np.linspace(s, 0, r)
    return e

def saw(f, n):
    t = np.arange(n) / FS
    # band-limited-ish saw: sum a few harmonics below 3.4 kHz
    y = np.zeros(n)
    k = 1
    while f * k < 3400 and k < 12:
        y += ((-1) ** (k + 1)) * np.sin(2 * math.pi * f * k * t) / k
        k += 1
    return y * 2 / math.pi

def tri(f, n):
    t = np.arange(n) / FS
    return signal.sawtooth(2 * math.pi * f * t, 0.5)

def kick(n):
    t = np.arange(n) / FS
    f = 150 * np.exp(-t * 25) + 45
    return np.sin(2 * math.pi * np.cumsum(f) / FS) * np.exp(-t * 12)

def hat(n, rng):
    t = np.arange(n) / FS
    return rng.standard_normal(n) * np.exp(-t * 60) * 0.5

def render(seconds, seed=7):
    rng = np.random.default_rng(seed)
    bpm = 112
    beat = int(FS * 60 / bpm)
    bar = beat * 4
    nbars = int(math.ceil(seconds * FS / bar))
    total = nbars * bar
    out = np.zeros(total)

    # I–V–vi–IV in A minor-ish colour: Am F C G (MIDI roots), 1 bar each
    progression = [(57, [0, 3, 7]), (53, [0, 4, 7]), (48, [0, 4, 7]), (55, [0, 4, 7])]
    for b in range(nbars):
        root, chord = progression[b % 4]
        start = b * bar
        # bass: root on beats 1 and 3, fifth on 2 and 4
        for i in range(4):
            f = note(root - 12 + (0 if i % 2 == 0 else 7))
            n = beat
            seg = tri(f, n) * env(n, 40, 400, 0.6, 600, n) * 0.45
            out[start + i*beat : start + i*beat + n] += seg
        # arpeggio: 16ths cycling chord tones over two octaves
        tones = [root + c for c in chord] + [root + 12 + c for c in chord]
        step = beat // 4
        for i in range(16):
            f = note(tones[(i * 3) % len(tones)])
            n = step
            seg = saw(f, n) * env(n, 20, 300, 0.4, 200, n) * 0.28
            out[start + i*step : start + i*step + n] += seg
        # pad: chord held, soft
        for c in chord:
            f = note(root + c)
            seg = np.sin(2 * math.pi * f * np.arange(bar) / FS) * env(bar, 2000, 1000, 0.8, 3000, bar) * 0.10
            out[start:start + bar] += seg
        # drums
        for i in range(4):
            k = kick(beat // 2)
            out[start + i*beat : start + i*beat + len(k)] += k * 0.8
        for i in range(8):
            h = hat(beat // 4, rng)
            pos = start + i * (beat // 2) + beat // 4
            out[pos : pos + len(h)] += h * 0.12

    # band-limit to the NBFM voice channel: 150–3400 Hz
    sos = signal.butter(4, [150, 3400], btype="band", fs=FS, output="sos")
    out = signal.sosfiltfilt(sos, out)
    # gentle compression + normalise to ~-1 dBFS
    out = np.tanh(out * 1.6)
    out /= np.max(np.abs(out)) / 0.89

    # trim to zero crossings at both ends for a click-free loop
    zc = np.where(np.diff(np.signbit(out)))[0]
    first, last = zc[0] + 1, zc[-1] + 1
    return out[first:last]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seconds", type=float, default=30)
    ap.add_argument("--out", default="../music_clip.h")
    ap.add_argument("--wav", default=None)
    a = ap.parse_args()

    y = render(a.seconds)
    pcm = np.clip(np.round(y * 127), -127, 127).astype(np.int8)
    if a.wav:
        from scipy.io import wavfile
        wavfile.write(a.wav, FS, (pcm.astype(np.int16) * 256))
    with open(a.out, "w") as f:
        f.write("/* SPDX-License-Identifier: CC0-1.0\n"
                " * music_clip.h - synthesised music loop for NBFM TX loop tests.\n"
                " * Generated by tools/gen_music_clip.py (original synthesis, no samples).\n"
                f" * {FS} Hz, int8 PCM, 150-3400 Hz band-limited, loop points on zero crossings.\n"
                " * DUMMY LOAD / CABLE ONLY - broadcasting music on the air is not permitted\n"
                " * under amateur radio regulations.\n */\n"
                "#ifndef MUSIC_CLIP_H\n#define MUSIC_CLIP_H\n#include <stdint.h>\n"
                f"#define MUSIC_CLIP_FS   {FS}u\n#define MUSIC_CLIP_LEN  {len(pcm)}u\n"
                f"static const int8_t music_clip[MUSIC_CLIP_LEN] = {{\n")
        for i in range(0, len(pcm), 20):
            f.write("  " + ",".join(f"{v:4d}" for v in pcm[i:i+20]) + ",\n")
        f.write("};\n#endif /* MUSIC_CLIP_H */\n")
    print(f"wrote {a.out}: {len(pcm)} samples, {len(pcm)/FS:.1f} s")

if __name__ == "__main__":
    main()
