#!/usr/bin/env python3
"""Convert any audio file into music_clip.h for NBFM TX loop tests.

Pipeline: decode (ffmpeg) -> mono -> pick the loudest N-second window
-> 150-3400 Hz band-pass -> 8000 Hz -> soft limit -> int8 -> trim to zero
crossings -> C header (MUSIC_CLIP_FS / MUSIC_CLIP_LEN / music_clip[]).

Usage: python3 make_music_clip.py track.mp3 --seconds 30 --out ../music_clip.h \
          --source "Title - Artist, licence, URL"
Requires ffmpeg on PATH, numpy, scipy.
Dummy load / cable only: broadcasting music on the air is not permitted.
"""
import argparse, subprocess, sys
import numpy as np
from scipy import signal

FS = 8000

def decode(path, fs=FS):
    cmd = ["ffmpeg", "-v", "error", "-i", path, "-ac", "1", "-ar", str(fs),
           "-f", "f32le", "-"]
    raw = subprocess.run(cmd, capture_output=True, check=True).stdout
    return np.frombuffer(raw, dtype=np.float32).astype(np.float64)

def loudest_window(x, n):
    if len(x) <= n:
        return 0
    # RMS over 0.5 s blocks, sliding sum over the window
    blk = FS // 2
    e = np.array([np.mean(x[i:i+blk]**2) for i in range(0, len(x) - blk, blk)])
    w = n // blk
    s = np.convolve(e, np.ones(w), "valid")
    return int(np.argmax(s)) * blk

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("audio")
    ap.add_argument("--seconds", type=float, default=30)
    ap.add_argument("--start", type=float, default=None, help="start (s); default: loudest window")
    ap.add_argument("--out", default="../music_clip.h")
    ap.add_argument("--wav", default=None)
    ap.add_argument("--source", default="(fill in title, artist, licence, URL)")
    a = ap.parse_args()

    x = decode(a.audio)
    n = int(a.seconds * FS)
    start = int(a.start * FS) if a.start is not None else loudest_window(x, n)
    seg = x[start:start + n]

    sos = signal.butter(4, [150, 3400], btype="band", fs=FS, output="sos")
    seg = signal.sosfiltfilt(sos, seg)
    seg = np.tanh(seg / (np.percentile(np.abs(seg), 99) + 1e-9) * 1.2)
    seg /= np.max(np.abs(seg)) / 0.9
    # fade edges 20 ms, then cut to zero crossings for a click-free loop
    f = int(0.02 * FS)
    seg[:f] *= np.linspace(0, 1, f); seg[-f:] *= np.linspace(1, 0, f)
    zc = np.where(np.diff(np.signbit(seg)))[0]
    seg = seg[zc[0] + 1: zc[-1] + 1]

    pcm = np.clip(np.round(seg * 127), -127, 127).astype(np.int8)
    if a.wav:
        from scipy.io import wavfile
        wavfile.write(a.wav, FS, pcm.astype(np.int16) * 256)
    with open(a.out, "w") as fh:
        fh.write("/* music_clip.h - embedded music excerpt for NBFM TX loop tests.\n"
                 f" * Source: {a.source}\n"
                 f" * Excerpt {start/FS:.1f}-{(start+n)/FS:.1f} s; {FS} Hz, int8 PCM,\n"
                 " * 150-3400 Hz band-limited, loop points on zero crossings.\n"
                 " * Generated by tools/make_music_clip.py.\n"
                 " * DUMMY LOAD / CABLE ONLY - broadcasting music on the air is not\n"
                 " * permitted under amateur radio regulations.\n */\n"
                 "#ifndef MUSIC_CLIP_H\n#define MUSIC_CLIP_H\n#include <stdint.h>\n"
                 f"#define MUSIC_CLIP_FS   {FS}u\n#define MUSIC_CLIP_LEN  {len(pcm)}u\n"
                 "static const int8_t music_clip[MUSIC_CLIP_LEN] = {\n")
        for i in range(0, len(pcm), 20):
            fh.write("  " + ",".join(f"{v:4d}" for v in pcm[i:i+20]) + ",\n")
        fh.write("};\n#endif /* MUSIC_CLIP_H */\n")
    print(f"{a.out}: {len(pcm)} samples ({len(pcm)/FS:.1f} s) from {start/FS:.1f} s")

if __name__ == "__main__":
    main()
